### ISSUE TITLE
Cannot create shell with custom certificates 

### ISSUE THREAD

**Issue by ptonner** [cachix/devenv#1237]
**Describe the bug**
I'm using `devenv` on a work machine, where custom certificates are injected with Zscaler. I've set `security.pki.certificates` in my nixos config, which has generally addressed the issue (I can run general `nix` commands without issue). But trying to create a shell with devenv does not work:

```sh
> RUST_BACKTRACE=full devenv shell
• Building shell ...
thread 'main' panicked at devenv/src/command.rs:284:26:
Failed to get cache: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("cachix.org")), port: None, path: "/api/v1/cache/devenv", query: None, fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 167772294, library: "SSL routines", function: "tls_post_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1889 }]))) }, X509VerifyResult { code: 2, error: "unable to get issuer certificate" })) }
stack backtrace:
   0:     0xaaaabf90ba54 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h75dbf07dc864c0bd
   1:     0xaaaabf9472f4 - core::fmt::write::h0c7806eb64ac0461
   2:     0xaaaabf8f8f48 - std::io::Write::write_fmt::ha53e993f45f43425
   3:     0xaaaabf90b87c - std::sys_common::backtrace::print::hb1055ea5fa282e57
   4:     0xaaaabf90c38c - std::panicking::default_hook::{{closure}}::h9bc2adbd2b89efe9
   5:     0xaaaabf90c09c - std::panicking::default_hook::h55811f2d21d601c1
   6:     0xaaaabf90c944 - std::panicking::rust_panic_with_hook::h976eed390f682de4
   7:     0xaaaabf90c7fc - std::panicking::begin_panic_handler::{{closure}}::h98a1c1b557857ce3
   8:     0xaaaabf90bca4 - std::sys_common::backtrace::__rust_end_short_backtrace::h70cf8b31899cdba4
   9:     0xaaaabf90c59c - rust_begin_unwind
  10:     0xaaaabf5f6734 - core::panicking::panic_fmt::h0971f4e715269fcb
  11:     0xaaaabf5f6aa8 - core::result::unwrap_failed::h73b70ef0c4d97d03
  12:     0xaaaabf5fefd0 - devenv::command::<impl devenv::App>::prepare_command::hf8c09b348137dbe1
  13:     0xaaaabf5fbb64 - devenv::command::<impl devenv::App>::run_nix::hcd20f469f09515a0
  14:     0xaaaabf60c2a4 - devenv::App::get_dev_environment::h4848001b2f84f86b
  15:     0xaaaabf608704 - devenv::App::prepare_shell::h83197b9cd4e9edf5
  16:     0xaaaabf602b4c - devenv::main::h41255c1257229c5d
  17:     0xaaaabf669af0 - std::sys_common::backtrace::__rust_begin_short_backtrace::h14f1e4a0403543e0
  18:     0xaaaabf6583d8 - std::rt::lang_start::{{closure}}::hd0e66ad970d06b52
  19:     0xaaaabf90c450 - std::panicking::try::h1ea181fc1a5f2df1
  20:     0xaaaabf914f00 - std::rt::lang_start_internal::h739eda15a5578387
  21:     0xaaaabf619254 - main
  22:     0xffff83e2c500 - __libc_start_call_main
  23:     0xffff83e2c5d8 - __libc_start_main@@GLIBC_2.34
  24:     0xaaaabf5f6e30 - _start
  25:                0x0 - <unknown>
✔ Building shell in 0.5s.
```

**To reproduce**
Not sure how to provide generally reproducible info, b/c it's a custom certificate

**Version**
 
devenv 1.0.5 (aarch64-linux)

**Comment by sandydoo** [comment]
@ptonner, could you please give this branch a try: https://github.com/cachix/devenv/pull/1238

**Comment by ptonner** [comment]
thanks for the fast turnaround! unfortunately it didn't work for me

```sh
> nix shell github:cachix/devenv/use-native-cert-store
> which devenv
/nix/store/063n1qkghq66y6rj1aciq27b4sm8x1rk-devenv-1.0.5/bin/devenv
> RUST_BACKTRACE=full devenv shell
• Building shell ...
thread 'main' panicked at devenv/src/command.rs:286:51:
Failed to get cache: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("cachix.org")), port: None, path: "/api/v1/cache/devenv", query: None, fragment: None }, source: hyper::Error(Connect, Ssl(Error { code: ErrorCode(1), cause: Some(Ssl(ErrorStack([Error { code: 167772294, library: "SSL routines", function: "tls_post_process_server_certificate", reason: "certificate verify failed", file: "ssl/statem/statem_clnt.c", line: 1889 }]))) }, X509VerifyResult { code: 2, error: "unable to get issuer certificate" })) }
stack backtrace:
   0:     0xaaaad417f0c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hcea0e942556235da
   1:     0xaaaad41a3914 - core::fmt::write::hc71024ef34e28312
   2:     0xaaaad415b348 - std::io::Write::write_fmt::h41d92926d93a7bb9
   3:     0xaaaad417eeec - std::sys_common::backtrace::print::h7819a8115109f212
   4:     0xaaaad4180218 - std::panicking::default_hook::{{closure}}::hb0ffd4171483a401
   5:     0xaaaad417ff44 - std::panicking::default_hook::hb5291fb36b5b8917
   6:     0xaaaad41807d8 - std::panicking::rust_panic_with_hook::hc474b468a8118958
   7:     0xaaaad4180694 - std::panicking::begin_panic_handler::{{closure}}::hf357bf09ed76c036
   8:     0xaaaad417f314 - std::sys_common::backtrace::__rust_end_short_backtrace::h904e6ea50bec8cae
   9:     0xaaaad4180434 - rust_begin_unwind
  10:     0xaaaad3dc275c - core::panicking::panic_fmt::h278e3cddb1b6e4ac
  11:     0xaaaad3dc25e0 - core::result::unwrap_failed::h82776741042be38e
  12:     0xaaaad3dca4f8 - devenv::command::<impl devenv::App>::prepare_command::h417cc773b3aa99b8
  13:     0xaaaad3dc7dd0 - devenv::command::<impl devenv::App>::run_nix::h698e48742579b7e5
  14:     0xaaaad3dd75e0 - devenv::App::get_dev_environment::hd8f2e09a53fb53c1
  15:     0xaaaad3dd3a10 - devenv::App::prepare_shell::h0546863ef40deaf0
  16:     0xaaaad3dcdd10 - devenv::main::h614e3978473ac29d
  17:     0xaaaad3e20808 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf1ffc8aafce73f8f
  18:     0xaaaad3e3ca64 - std::rt::lang_start::{{closure}}::h2236a5465481f2f6
  19:     0xaaaad41802dc - std::panicking::try::hb14e0e162f35f3ef
  20:     0xaaaad417b328 - std::rt::lang_start_internal::h6fa7342305762cae
  21:     0xaaaad3de44a8 - main
  22:     0xffffb30fc500 - __libc_start_call_main
  23:     0xffffb30fc5d8 - __libc_start_main@@GLIBC_2.34
  24:     0xaaaad3dc2bb0 - _start
  25:                0x0 - <unknown>
✔ Building shell in 0.5s.
```

**Comment by ptonner** [comment]
Just FYI, this may have been an error on my part - I hadn't set up all the certificates. Not sure why base nix was able to work around this, but things seem to be working for me now. Will close unless something else shows up
