### ISSUE TITLE
go panics on container deploy to fly

### ISSUE THREAD

**Issue by codegod100** [cachix/devenv#1472]
```
2024-09-25T02:13:04.044 app[683d3d2fd73668] sea [info] Succeeded devenv:python:poetry 3344ms

2024-09-25T02:13:04.044 app[683d3d2fd73668] sea [info] 1 Pending, 1 Succeeded 3.38s

2024-09-25T02:13:04.095 app[683d3d2fd73668] sea [info] Succeeded devenv:python:poetry 3344ms

2024-09-25T02:13:04.095 app[683d3d2fd73668] sea [info] Succeeded devenv:enterShell 2ms

2024-09-25T02:13:04.095 app[683d3d2fd73668] sea [info] 2 Succeeded 3.43s

2024-09-25T02:13:04.096 app[683d3d2fd73668] sea [info] ✨ devenv 1.2.0 is newer than devenv input in devenv.lock. Run `devenv update` to sync.

2024-09-25T02:13:04.097 app[683d3d2fd73668] sea [info] hello from devenv

2024-09-25T02:13:04.114 app[683d3d2fd73668] sea [info] git version 2.44.0

2024-09-25T02:13:04.236 app[683d3d2fd73668] sea [info] {"level":"warn","error":"open /env/.config/process-compose/settings.yaml: no such file or directory","time":"2024-09-25T02:13:04Z","message":"Error reading settings file /env/.config/process-compose/settings.yaml"}

2024-09-25T02:13:04.249 app[683d3d2fd73668] sea [info] panic: open /dev/tty: no such device or address

2024-09-25T02:13:04.249 app[683d3d2fd73668] sea [info] goroutine 8 [running]:

2024-09-25T02:13:04.249 app[683d3d2fd73668] sea [info] github.com/f1bonacc1/process-compose/src/tui.SetupTui({0xe9e960?, 0xc00044f5e0?}, {0xc00034bf78, 0x3, 0x0?})

2024-09-25T02:13:04.249 app[683d3d2fd73668] sea [info] github.com/f1bonacc1/process-compose/src/tui/view.go:505 +0x156

2024-09-25T02:13:04.249 app[683d3d2fd73668] sea [info] github.com/f1bonacc1/process-compose/src/cmd.startTui({0xe9e960, 0xc00044f5e0})

2024-09-25T02:13:04.249 app[683d3d2fd73668] sea [info] github.com/f1bonacc1/process-compose/src/cmd/project_runner.go:89 +0x1d5

2024-09-25T02:13:04.249 app[683d3d2fd73668] sea [info] created by github.com/f1bonacc1/process-compose/src/cmd.runTui in goroutine 1

2024-09-25T02:13:04.249 app[683d3d2fd73668] sea [info] github.com/f1bonacc1/process-compose/src/cmd/project_runner.go:73 +0x65

2024-09-25T02:13:04.600 app[683d3d2fd73668] sea [info] INFO Main child exited normally with code: 0

2024-09-25T02:13:04.614 app[683d3d2fd73668] sea [info] INFO Starting clean up.

2024-09-25T02:13:04.684 app[683d3d2fd73668] sea [info] WARN could not unmount /rootfs: EINVAL: Invalid argument
```

**Comment by domenkozar** [comment]
> panic: open /dev/tty: no such device or address

IIRC this was fixed a long time ago in process-compose reopen if it persist in latest versions.
