### ISSUE TITLE
Elasticsearch plugins not updated

### ISSUE THREAD

**Issue by fballiano** [cachix/devenv#342]
**Describe the bug**

In my [magento2-devenv](https://github.com/fballiano/magento2-devenv) setup I'm using elasticsearch (since it's mandatory for magento2) and it needs 2 plugins: analysis-phonetic and analysis-icu.

But when I edit my [devenv.nix](https://github.com/fballiano/magento2-devenv/blob/main/devenv.nix) adding this line:
```
  services.elasticsearch.plugins = [ pkgs.elasticsearchPlugins.analysis-icu ];
```

`devenv up` doesn't start anymore because the plugins are not updated with elasticsearch itself:

```
pkgs.elasticsearch                                    6.8.21       Open Source, Distributed, RESTful Search Engine
pkgs.elasticsearch-curator                            5.8.4        Curate, or manage, your Elasticsearch indices and snapshots
pkgs.elasticsearch-oss                                6.8.21       Open Source, Distributed, RESTful Search Engine
pkgs.elasticsearch6                                   6.8.21       Open Source, Distributed, RESTful Search Engine
pkgs.elasticsearch6-oss                               6.8.21       Open Source, Distributed, RESTful Search Engine
pkgs.elasticsearch7                                   7.17.4       Open Source, Distributed, RESTful Search Engine
pkgs.elasticsearchPlugins.analysis-icu                6.8.21       The ICU Analysis plugin integrates the Lucene ICU module into elasticsearch
pkgs.elasticsearchPlugins.analysis-lemmagen           6.8.21       LemmaGen Analysis plugin provides jLemmaGen lemmatizer as Elasticsearch token filter
pkgs.elasticsearchPlugins.analysis-phonetic           6.8.21       The Phonetic Analysis plugin integrates phonetic token filter analysis with elasticsearch
pkgs.elasticsearchPlugins.discovery-ec2               6.8.21       The EC2 discovery plugin uses the AWS API for unicast discovery.
pkgs.elasticsearchPlugins.ingest-attachment           6.8.21       Ingest processor that uses Apache Tika to extract contents
pkgs.elasticsearchPlugins.repository-gcs              6.8.21       The GCS repository plugin adds support for using Google Cloud Storage as a repository for Snapshot/Restore.
pkgs.elasticsearchPlugins.repository-s3               6.8.21       The S3 repository plugin adds support for using AWS S3 as a repository for Snapshot/Restore.
pkgs.elasticsearchPlugins.search-guard                6.8.21-25.6  Elasticsearch plugin that offers encryption, authentication, and authorisation.
```

since the plugins are version 6.8 while elasticsearch is version7, the whole `devenv up` breaks.

**Version**
 
0.5

**Comment by domenkozar** [comment]
Try:

```nix
services.elasticsearch.plugins = [ pkgs.elasticsearch7Plugins.analysis-icu ];
```

**Comment by fballiano** [comment]
auch I didn't think about that since the "devenv search" wasn't returning those packages.

kgs.elasticsearch7Plugins.analysis-icu works fine but if I enable kgs.elasticsearch7Plugins.analysis-phonetic it breaks again with:

```
09:39:00 elasticsearch.1   | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
09:39:01 elasticsearch.1   | [2023-02-01T09:39:01,175][WARN ][o.e.c.l.LogConfigurator  ] [MBP-Fab.local] Some logging configurations have %marker but don't have %node_name. We will automatically add %node_name to the pattern to ease the migration for users who customize log4j2.properties but will stop this behavior in 7.0. You should manually replace `%node_name` with `[%node_name]%marker ` in these locations:
09:39:01 elasticsearch.1   |   /Users/fab/Projects/magento2-devenv/.devenv/state/elasticsearch/config/log4j2.properties
09:39:01 elasticsearch.1   | [2023-02-01T09:39:01,941][INFO ][o.e.n.Node               ] [MBP-Fab.local] version[7.17.4], pid[52152], build[default/tar/79878662c54c886ae89206c685d9f1051a9d6411/2022-05-18T18:04:20.964345128Z], OS[Mac OS X/11.1/x86_64], JVM[Azul Systems, Inc./OpenJDK 64-Bit Server VM/11.0.11/11.0.11+9-LTS]
09:39:01 elasticsearch.1   | [2023-02-01T09:39:01,941][INFO ][o.e.n.Node               ] [MBP-Fab.local] JVM home [/nix/store/gyixx8hdfp7rxk6l4p71msz4ydgyf1rm-zulu11.48.21-ca-jdk-11.0.11/zulu-11.jdk/Contents/Home], using bundled JDK [false]
09:39:01 elasticsearch.1   | [2023-02-01T09:39:01,941][INFO ][o.e.n.Node               ] [MBP-Fab.local] JVM arguments [-Xshare:auto, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dio.netty.allocator.numDirectArenas=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Djava.io.tmpdir=/var/folders/xd/75gb9_h95vg1xprvtzt3lb640000gn/T/elasticsearch-17161675379563985961, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms1024m, -Xmx1024m, -XX:MaxDirectMemorySize=536870912, -Des.path.home=/Users/fab/Projects/magento2-devenv/.devenv/state/elasticsearch, -Des.path.conf=/Users/fab/Projects/magento2-devenv/.devenv/state/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=tar, -Des.bundled_jdk=true]
09:39:03 elasticsearch.1   | [2023-02-01T09:39:03,569][ERROR][o.e.b.ElasticsearchUncaughtExceptionHandler] [MBP-Fab.local] uncaught exception in thread [main]
09:39:03 elasticsearch.1   | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: failed to load plugin analysis-phonetic while checking for jar hell
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112) ~[elasticsearch-cli-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.cli.Command.main(Command.java:77) ~[elasticsearch-cli-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | Caused by: java.lang.IllegalStateException: failed to load plugin analysis-phonetic while checking for jar hell
09:39:03 elasticsearch.1   | 	at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:693) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:531) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:170) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.node.Node.<init>(Node.java:411) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	... 6 more
09:39:03 elasticsearch.1   | Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/nix/store/1642h3h4l3hwjss4fjm87k9hh7k5mfs4-elasticsearch-analysis-phonetic-7.17.4/plugins/analysis-phonetic/analysis-phonetic-7.17.4.jar" "read")
09:39:03 elasticsearch.1   | 	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472) ~[?:?]
09:39:03 elasticsearch.1   | 	at java.security.AccessController.checkPermission(AccessController.java:897) ~[?:?]
09:39:03 elasticsearch.1   | 	at java.lang.SecurityManager.checkPermission(SecurityManager.java:322) ~[?:?]
09:39:03 elasticsearch.1   | 	at java.lang.SecurityManager.checkRead(SecurityManager.java:661) ~[?:?]
09:39:03 elasticsearch.1   | 	at java.util.zip.ZipFile.<init>(ZipFile.java:250) ~[?:?]
09:39:03 elasticsearch.1   | 	at java.util.zip.ZipFile.<init>(ZipFile.java:191) ~[?:?]
09:39:03 elasticsearch.1   | 	at java.util.jar.JarFile.<init>(JarFile.java:348) ~[?:?]
09:39:03 elasticsearch.1   | 	at java.util.jar.JarFile.<init>(JarFile.java:319) ~[?:?]
09:39:03 elasticsearch.1   | 	at java.util.jar.JarFile.<init>(JarFile.java:258) ~[?:?]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.jdk.JarHell.checkJarHell(JarHell.java:180) ~[elasticsearch-core-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:689) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:531) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:170) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.node.Node.<init>(Node.java:411) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.node.Node.<init>(Node.java:309) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166) ~[elasticsearch-7.17.4.jar:7.17.4]
09:39:03 elasticsearch.1   | 	... 6 more
09:39:03 elasticsearch.1   | uncaught exception in thread [main]
09:39:03 elasticsearch.1   | java.lang.IllegalStateException: failed to load plugin analysis-phonetic while checking for jar hell
09:39:03 elasticsearch.1   | Likely root cause: java.security.AccessControlException: access denied ("java.io.FilePermission" "/nix/store/1642h3h4l3hwjss4fjm87k9hh7k5mfs4-elasticsearch-analysis-phonetic-7.17.4/plugins/analysis-phonetic/analysis-phonetic-7.17.4.jar" "read")
09:39:03 elasticsearch.1   | 	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
09:39:03 elasticsearch.1   | 	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
09:39:03 elasticsearch.1   | 	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
09:39:03 elasticsearch.1   | 	at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:661)
09:39:03 elasticsearch.1   | 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:250)
09:39:03 elasticsearch.1   | 	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
09:39:03 elasticsearch.1   | 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:348)
09:39:03 elasticsearch.1   | 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:319)
09:39:03 elasticsearch.1   | 	at java.base/java.util.jar.JarFile.<init>(JarFile.java:258)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.jdk.JarHell.checkJarHell(JarHell.java:180)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:689)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:531)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:170)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.node.Node.<init>(Node.java:411)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.node.Node.<init>(Node.java:309)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:234)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:234)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:434)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:166)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:157)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:77)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:112)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.cli.Command.main(Command.java:77)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:122)
09:39:03 elasticsearch.1   | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:80)
09:39:03 elasticsearch.1   | For complete error details, refer to the log at /Users/fab/Projects/magento2-devenv/.devenv/state/elasticsearch/logs/elasticsearch.log
09:39:03 system            | elasticsearch.1 stopped (rc=1)
```

but the /Users/fab/Projects/magento2-devenv/.devenv/state/elasticsearch/logs/elasticsearch.log file doesn't exist.

**Comment by domenkozar** [comment]
That looks like a bug in https://github.com/NixOS/nixpkgs, I'm not familiar with elasticsearch enough to give any directions :)

**Comment by fballiano** [comment]
opened https://github.com/NixOS/nixpkgs/issues/213951
