### ISSUE TITLE
OSError: AF_UNIX path too long

### ISSUE THREAD

**Issue by lzhu-aurorasolar** [cachix/devenv#540]
**Describe the bug**

I'm getting the following Traceback when trying to run `pytest` within a devenv shell. The tests run without issues outside of devenv shell either on local environment or in a Docker container.

```python
Process SyncManager-1:
Traceback (most recent call last):
  File "/nix/store/r23sw9iy2jdrh59dsq8mic6ahkcijijr-python3-3.10.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nix/store/r23sw9iy2jdrh59dsq8mic6ahkcijijr-python3-3.10.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nix/store/r23sw9iy2jdrh59dsq8mic6ahkcijijr-python3-3.10.10/lib/python3.10/multiprocessing/managers.py", line 591, in _run_server
    server = cls._Server(registry, address, authkey, serializer)
  File "/nix/store/r23sw9iy2jdrh59dsq8mic6ahkcijijr-python3-3.10.10/lib/python3.10/multiprocessing/managers.py", line 156, in __init__
    self.listener = Listener(address=address, backlog=16)
  File "/nix/store/r23sw9iy2jdrh59dsq8mic6ahkcijijr-python3-3.10.10/lib/python3.10/multiprocessing/connection.py", line 448, in __init__
    self._listener = SocketListener(address, family, backlog)
  File "/nix/store/r23sw9iy2jdrh59dsq8mic6ahkcijijr-python3-3.10.10/lib/python3.10/multiprocessing/connection.py", line 591, in __init__
    self._socket.bind(address)
OSError: AF_UNIX path too long
```

**To reproduce**
Please provide an [sscce](http://sscce.org) by [creating a gist](https://gist.github.com/) using `devenv.nix`, `devenv.yaml`, and optionally `devenv.lock`.

`devenv.nix`:

```nix
{ pkgs, ... }:

{

  name = "app";

  # https://devenv.sh/packages/
  packages = [
    pkgs.git
    pkgs.direnv
    pkgs.gdal
    pkgs.postgresql_14
    pkgs.openssl_1_1
    pkgs.postgis
    pkgs.geos
    pkgs.redis
  ];

  # https://devenv.sh/languages/
  languages.python.enable = true;
  languages.python.venv.enable = true;

  # https://devenv.sh/scripts/
  scripts.install-reqs.exec = ''
    pip install --upgrade pip
    pip install -r requirements.txt
  '';

  enterShell = ''
    install-reqs
  '';

  # See full reference at https://devenv.sh/reference/options/
  services.postgres.enable = true;
  services.redis.enable = true;
}
```

`devenv.yaml`:

```yaml
inputs:
  nixpkgs:
    url: github:NixOS/nixpkgs/nixpkgs-unstable
```

`devenv.lock`:

```json
{
  "nodes": {
    "devenv": {
      "locked": {
        "dir": "src/modules",
        "lastModified": 1681818540,
        "narHash": "sha256-cokgv9kZM+rQtTI45x3z8WuCO4atL0UNtQWICc+v1WM=",
        "owner": "cachix",
        "repo": "devenv",
        "rev": "c67a0fcf40a384f955d21494cb6d72a562cf82cf",
        "type": "github"
      },
      "original": {
        "dir": "src/modules",
        "owner": "cachix",
        "repo": "devenv",
        "type": "github"
      }
    },
    "flake-compat": {
      "flake": false,
      "locked": {
        "lastModified": 1673956053,
        "narHash": "sha256-4gtG9iQuiKITOjNQQeQIpoIB6b16fm+504Ch3sNKLd8=",
        "owner": "edolstra",
        "repo": "flake-compat",
        "rev": "35bb57c0c8d8b62bbfd284272c928ceb64ddbde9",
        "type": "github"
      },
      "original": {
        "owner": "edolstra",
        "repo": "flake-compat",
        "type": "github"
      }
    },
    "flake-utils": {
      "locked": {
        "lastModified": 1667395993,
        "narHash": "sha256-nuEHfE/LcWyuSWnS8t12N1wc105Qtau+/OdUAjtQ0rA=",
        "owner": "numtide",
        "repo": "flake-utils",
        "rev": "5aed5285a952e0b949eb3ba02c12fa4fcfef535f",
        "type": "github"
      },
      "original": {
        "owner": "numtide",
        "repo": "flake-utils",
        "type": "github"
      }
    },
    "gitignore": {
      "inputs": {
        "nixpkgs": [
          "pre-commit-hooks",
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1660459072,
        "narHash": "sha256-8DFJjXG8zqoONA1vXtgeKXy68KdJL5UaXR8NtVMUbx8=",
        "owner": "hercules-ci",
        "repo": "gitignore.nix",
        "rev": "a20de23b925fd8264fd7fad6454652e142fd7f73",
        "type": "github"
      },
      "original": {
        "owner": "hercules-ci",
        "repo": "gitignore.nix",
        "type": "github"
      }
    },
    "nixpkgs": {
      "locked": {
        "lastModified": 1681903854,
        "narHash": "sha256-U3vbSEdct4aUu+vk3YsBiwokN3th4Jvde7S8gnVmeAA=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "bb2009ca185d97813e75736c2b8d1d8bb81bde05",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixpkgs-unstable",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "nixpkgs-stable": {
      "locked": {
        "lastModified": 1678872516,
        "narHash": "sha256-/E1YwtMtFAu2KUQKV/1+KFuReYPANM2Rzehk84VxVoc=",
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "9b8e5abb18324c7fe9f07cb100c3cd4a29cda8b8",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-22.11",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "pre-commit-hooks": {
      "inputs": {
        "flake-compat": "flake-compat",
        "flake-utils": "flake-utils",
        "gitignore": "gitignore",
        "nixpkgs": [
          "nixpkgs"
        ],
        "nixpkgs-stable": "nixpkgs-stable"
      },
      "locked": {
        "lastModified": 1681831107,
        "narHash": "sha256-pXl3DPhhul9NztSetUJw2fcN+RI3sGOYgKu29xpgnqw=",
        "owner": "cachix",
        "repo": "pre-commit-hooks.nix",
        "rev": "b7ca8f6fff42f6af75c17f9438fed1686b7d855d",
        "type": "github"
      },
      "original": {
        "owner": "cachix",
        "repo": "pre-commit-hooks.nix",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "devenv": "devenv",
        "nixpkgs": "nixpkgs",
        "pre-commit-hooks": "pre-commit-hooks"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

**Version**
 
devenv: 0.6.2

**Comment by domenkozar** [comment]
Seeing similar issues on CI:

```
psql: error: Unix-domain socket path "/Users/hetzner/actions-runner/_work/devenv/devenv/examples/postgres/.devenv/state/postgres/.s.PGSQL.5432" is too long (maximum 103 bytes)
```

**Comment by domenkozar** [comment]
@lzhu-aurorasolar what's the `$PWD` of where you run devenv?

**Comment by lzhu-aurorasolar** [comment]
@domenkozar `/Users/<7-char username>/work/<11-char directory name>/<10-char repository name>`

**Comment by domenkozar** [comment]
I wonder, does it work if you add `process.implementation = "process-compose";` to `devenv.nix`?

**Comment by lzhu-aurorasolar** [comment]
> I wonder, does it work if you add `process.implementation = "process-compose";` to `devenv.nix`?

@domenkozar tried this out, I am still seeing the `OSError: AF_UNIX path too long` error.

**Comment by DaniruKun** [comment]
Have the same issue when trying to run Puma:
```
puma/binder.rb:422:in `initialize': too long unix socket path (108bytes given but 104bytes max) (ArgumentError)

        s = UNIXServer.new path.sub(/\A@/, "\0") # check for abstract UNIXSocket
```

Example path: `/var/folders/7w/vj7k1xyx5h9510b_dbj46_y40000gn/T/nix-shell.XXXXXX.nePlinQWw8/puma-status-1706968248025-33712`

**Comment by domenkozar** [comment]
@DaniruKun can you share your `devenv.nix`?
