### ISSUE TITLE
Poetry install failure with "no module named 'pip'" error.

### ISSUE THREAD

**Issue by shahinism** [cachix/devenv#635]
**Describe the bug**

I am attempting to enable the utilization of the `poetry` package manager within my `devenv` environment, utilizing the provided configuration:
```nix
  languages.python.poetry.enable = true;
  languages.python.package = pkgs.python39;
  languages.python.enable = true;

# Also tried with the default Python version
  languages.python.poetry.enable = true;
  languages.python.enable = true;
```
 The environment setup has been successful, and everything appears to be in order. However, upon attempting to install a package, an error is encountered:

```
  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "/nix/store/civ85z9kj6by4280xsbbwfk22p026kcg-python3.10-pyproject-hooks-1.0.0/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/nix/store/civ85z9kj6by4280xsbbwfk22p026kcg-python3.10-pyproject-hooks-1.0.0/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/nix/store/civ85z9kj6by4280xsbbwfk22p026kcg-python3.10-pyproject-hooks-1.0.0/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/tmp3wggjcvo/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/tmp3wggjcvo/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/tmp/tmp3wggjcvo/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 487, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/tmp3wggjcvo/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 8, in <module>
  ModuleNotFoundError: No module named 'pip'
  

  at /nix/store/q0i03v49yzah6ygbb7j7ad1biwp4qch0-python3.10-poetry-1.4.2/lib/python3.10/site-packages/poetry/installation/chef.py:152 in _prepare
      148│ 
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│ 
      151│             if error is not None:
    → 152│                 raise error from None
      153│ 
      154│             return path
      155│ 
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
```
 It remains unclear whether this error stems from an issue within the `devenv` environment itself or from an upstream source. Nonetheless, a significant concern arises from the fact that it is currently impossible to align the version of `poetry` available in the official Nix repositories with the specific version of Python defined using the `languages.python.package` directive.

**To reproduce**
The full setup, can be found [here](https://gist.github.com/shahinism/f9ddc12958d09348e8dbc4e290c1bc19)

**Version**
 
**devenv version**: 0.6.2

**Comment by shahinism** [comment]
Figured the problem was related to KSQL package not being compatible with pep517.
