### ISSUE TITLE
`Microsoft.Diagnostics.NETCore.Client.ServerNotAvailableException: Process xxx not running compatible .NET runtime.` when running EventStore as a process

### ISSUE THREAD

**Issue by guizmaii** [cachix/devenv#710]
Hi,

I'm not sure this is the best place to ask my question but I don't know where to ask it. Sorry if it's not the  correct place.

I'm new to Nix and devenv. I'm trying to run [EventStore](https://www.eventstore.com/) in my "devenv".
For this, I had a look at these three links:
- Nix EventStore "recipe": https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/nosql/eventstore/default.nix
- Redis devenv declaration: https://github.com/cachix/devenv/blob/main/src/modules/services/redis.nix
- EventStore configuration for "dev mode": https://developers.eventstore.com/server/v20.10/installation.html#use-docker-compose

Copying the content of these links, I came up with:
```nix
{ pkgs, ... }:

{
  # https://devenv.sh/basics/
  env = {
    GREET = "devenv";
    # See https://developers.eventstore.com/server/v20.10/installation.html#use-docker-compose
    EVENTSTORE_CLUSTER_SIZE = 1;
    EVENTSTORE_RUN_PROJECTIONS = "All";
    EVENTSTORE_START_STANDARD_PROJECTIONS = true;
    EVENTSTORE_EXT_TCP_PORT = 1113;
    EVENTSTORE_HTTP_PORT = 2113;
    EVENTSTORE_INSECURE = true;
    EVENTSTORE_ENABLE_EXTERNAL_TCP = true;
  };

  # A .env file found, but dotenv integration is currently not enabled.
  # To enable it, set `dotenv.enable = true;` in your configuration.
  dotenv.enable = true;

  # https://devenv.sh/packages/
  packages = [
    pkgs.git
    pkgs.eventstore
  ];

  # https://devenv.sh/scripts/
  scripts.hello.exec = "echo hello from $GREET";

  enterShell = ''
    hello
    git --version
  '';

  # https://devenv.sh/languages/
  # languages.nix.enable = true;

  # https://devenv.sh/pre-commit-hooks/
  # pre-commit.hooks.shellcheck.enable = true;

  # https://devenv.sh/processes/
  # processes.ping.exec = "ping example.com";

  # See full reference at https://devenv.sh/reference/options/

  # Inpired from:
  #   - https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/nosql/eventstore/default.nix
  #   - https://github.com/cachix/devenv/blob/main/src/modules/services/redis.nix
  processes.eventstore = {
    exec = ''
      ${pkgs.eventstore}/bin/EventStore.ClusterNode \
        --db "$DEVENV_STATE/eventstore/data" \
        --index "$DEVENV_STATE/eventstore/index" \
        --log "$DEVENV_STATE/eventstore/log"
    '';
  };

  services.redis = {
    enable = true;
  };
  services.postgres = {
    enable = true;
    package = pkgs.postgresql_15;
    initialDatabases = [{ name = "myDB"; }];
  };
}
```

EventStore does start and it seems that I can push events into it.
But I'm not sure everything is working fine. 
The EventStore web UI doesn't seems to be able list my streams, for example, and in the server logs I have the following error:
```bash
...
20:52:07 eventstore.1 | [92383, 6,20:52:07.864,DBG] "streamExistenceFilter" has flushed at 11,513. Diff 796. Took 00:00:00.0236810
20:52:08 eventstore.1 | [92383,31,20:52:08.194,WRN] Error encountered while processing events
20:52:08 eventstore.1 | Microsoft.Diagnostics.NETCore.Client.ServerNotAvailableException: Process 92383 not running compatible .NET runtime.
20:52:08 eventstore.1 |    at Microsoft.Diagnostics.NETCore.Client.PidIpcEndpoint.GetDefaultAddress()
20:52:08 eventstore.1 |    at Microsoft.Diagnostics.NETCore.Client.PidIpcEndpoint.Connect(TimeSpan timeout)
20:52:08 eventstore.1 |    at Microsoft.Diagnostics.NETCore.Client.IpcClient.SendMessageGetContinuation(IpcEndpoint endpoint, IpcMessage message)
20:52:08 eventstore.1 |    at Microsoft.Diagnostics.NETCore.Client.EventPipeSession.Start(IpcEndpoint endpoint, IEnumerable`1 providers, Boolean requestRundown, Int32 circularBufferMB)
20:52:08 eventstore.1 |    at Microsoft.Diagnostics.NETCore.Client.DiagnosticsClient.StartEventPipeSession(IEnumerable`1 providers, Boolean requestRundown, Int32 circularBufferMB)
20:52:08 eventstore.1 |    at EventStore.Core.Services.Monitoring.Utils.EventCountersHelper.<Start>b__8_0() in /private/tmp/nix-build-EventStore-22.10.2.drv-0/source/src/EventStore.Core/Services/Monitoring/Utils/EventCountersHelper.cs:line 48
...
```

Any idea of what is wrong?
How can I get more information?

Thanks for your help 🙂
Jules

**Comment by domenkozar** [comment]
It does start fine for me using the following `devenv.nix` (which just removed a bunch of things from what you have):

```
{ pkgs, ... }:

{
  # https://devenv.sh/basics/
  env = {
    # See https://developers.eventstore.com/server/v20.10/installation.html#use-docker-compose
    EVENTSTORE_CLUSTER_SIZE = 1;
    EVENTSTORE_RUN_PROJECTIONS = "All";
    EVENTSTORE_START_STANDARD_PROJECTIONS = true;
    EVENTSTORE_EXT_TCP_PORT = 1113;
    EVENTSTORE_HTTP_PORT = 2113;
    EVENTSTORE_INSECURE = true;
    EVENTSTORE_ENABLE_EXTERNAL_TCP = true;
  };

  # Inpired from:
  #   - https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/nosql/eventstore/default.nix
  #   - https://github.com/cachix/devenv/blob/main/src/modules/services/redis.nix
  processes.eventstore = {
    exec = ''
      ${pkgs.eventstore}/bin/EventStore.ClusterNode \
        --db "$DEVENV_STATE/eventstore/data" \
        --index "$DEVENV_STATE/eventstore/index" \
        --log "$DEVENV_STATE/eventstore/log"
    '';
  };

  services.redis.enable = true;

  services.postgres = {
    enable = true;
    package = pkgs.postgresql_15;
    initialDatabases = [{ name = "myDB"; }];
  };
}
```

Maybe you have some specific .net things installed on your machine?

**Comment by guizmaii** [comment]
Maybe some additional details:
- I'm running on Mac
- The error happens after a few seconds.
   First, the server seems to be booting fine, blocking for a few seconds on this log line:
   ```sh
   22:31:17 eventstore.1 | [97094,14,22:31:17.943,INF] "InaugurationManager" in state (Leader, Initial): IGNORING "CheckInaugurationConditions". Not waiting for conditions.
   ```
   After these few seconds, the error happens.
- I'm not sure I have any version of .Net installed, being on macOS 🤔

**Comment by guizmaii** [comment]
Well, I decided to go with Docker Compose. It'll be easier for me. Less things to learn

**Comment by domenkozar** [comment]
It seems like eventstore is broken on darwin.
