### ISSUE TITLE
`ImportError` when running python with packages that include share libraries

### ISSUE THREAD

**Issue by Atry** [cachix/devenv#773]
**Describe the bug**
Python packages installed from `pip` cannot find `libstdc++.so.6`

**To reproduce**
Given the `flake.nix`

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-22.11";
    systems.url = "github:nix-systems/default";
    devenv.url = "github:cachix/devenv";
  };

  nixConfig = {
    extra-trusted-public-keys = "devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=";
    extra-substituters = "https://devenv.cachix.org";
  };

  outputs = { self, nixpkgs, devenv, systems, ... } @ inputs:
    let
      forEachSystem = nixpkgs.lib.genAttrs (import systems);
    in
    {
      devShells = forEachSystem
        (system:
          let
            pkgs = nixpkgs.legacyPackages.${system};
          in
          {
            default = devenv.lib.mkShell {
              inherit inputs pkgs;
              modules = [
                {
                  # https://devenv.sh/reference/options/
                  packages = [ pkgs.hello ];

                  enterShell = ''
                    python -m grpc_tools.protoc --help
                  '';

                  languages.python = {
                    enable = true;
                    venv = {
                      enable = true;
                      requirements = ''
                        grpcio-tools
                      '';
                    };
                  };
                }
              ];
            };
          });
    };
}

```

Run `nix develop --impure`, then I got the error
```
$ nix develop --impure
warning: Git tree '/home/atry/devenv-poetry' is dirty
Requirement already satisfied: grpcio-tools in ./.devenv/state/venv/lib/python3.10/site-packages (from -r /nix/store/zl8ljp68qhqs4gd836isanbq6z393arr-requirements.txt (line 1)) (1.56.2)
Requirement already satisfied: grpcio>=1.56.2 in ./.devenv/state/venv/lib/python3.10/site-packages (from grpcio-tools->-r /nix/store/zl8ljp68qhqs4gd836isanbq6z393arr-requirements.txt (line 1)) (1.56.2)
Requirement already satisfied: setuptools in ./.devenv/state/venv/lib/python3.10/site-packages (from grpcio-tools->-r /nix/store/zl8ljp68qhqs4gd836isanbq6z393arr-requirements.txt (line 1)) (65.5.0)
Requirement already satisfied: protobuf<5.0dev,>=4.21.6 in ./.devenv/state/venv/lib/python3.10/site-packages (from grpcio-tools->-r /nix/store/zl8ljp68qhqs4gd836isanbq6z393arr-requirements.txt (line 1)) (4.23.4)

[notice] A new release of pip is available: 23.0.1 -> 23.2.1
[notice] To update, run: pip install --upgrade pip
Traceback (most recent call last):
  File "/nix/store/zn2g96d0hhk5h8x7982m2gbbawgwsrvz-python3-3.10.11/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/zn2g96d0hhk5h8x7982m2gbbawgwsrvz-python3-3.10.11/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/atry/devenv-poetry/.devenv/state/venv/lib/python3.10/site-packages/grpc_tools/protoc.py", line 20, in <module>
    from grpc_tools import _protoc_compiler
ImportError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Version**
 
e91205acb792f6a49ea53ab04c04fbc2a85039cd

**Comment by Atry** [comment]
The following workaround can suppress the error. 
```nix
packages = [ pkgs.gcc11Stdenv.cc.cc.lib ]
```
However, Ubuntu native executables, e.g. `/usr/bin/git`, do not work with this workaround.

**Comment by Atry** [comment]
I think the best fix for this issue is to create a wrapper of `python` to set `LD_LIBRARY_PATH` and support [manylinux](https://peps.python.org/pep-0513/) ABI out-of-box, instead of setting a project-wise `LD_LIBRARY_PATH`.

**Comment by Atry** [comment]
I created a pull request helping resolving this issue.
https://github.com/NixOS/nixpkgs/pull/248777

**Comment by domenkozar** [comment]
I have created a test case here: https://github.com/cachix/devenv/blob/python-rewrite/tests/python-native-libs/devenv.nix

However for some reason it doesn't work still.

```
❯ python -c "import os;print(os.environ['LD_LIBRARY_PATH'])"
/home/domen/dev/cachix/devenv/.devenv/profile/lib

❯ ls .devenv/profile/lib|grep stdc++
libstdc++.so.6

❯ python -c "from ctypes.util import find_library;print(find_library('stdc++'))"
None

❯ python -c "from ctypes.util import find_library;print(find_library('GL'))"
libGL.so.1
```

**Comment by Atry** [comment]
I think `LD_LIBRARY_PATH` is fragile. Maybe we should not add `devenv.packages` to `LD_LIBRARY_PATH` by default? To me, `devenv.packages` stands for cli tools.

**Comment by domenkozar** [comment]
How about `languages.python.nativeDependencies`?

**Comment by domenkozar** [comment]
I'm think about `languages.python.libraries = config.packages`, so that it matches how other languages work, by picking it up from `packages`.

That allows anyone with an issue to go and explicitly set it if needed.

**Comment by domenkozar** [comment]
Exactly, only pass it to python by default, but can be changed.

**Comment by domenkozar** [comment]
[08a3497b59051c2839c8ced79d39687b8485ab26](https://github.com/NixOS/nixpkgs/issues/7307#issuecomment-1689673234)

**Comment by AleCandido** [comment]
Sorry to bump an old thread: this problem persists (also because none of the issue or PR related has been closed or merged).

I made a few trials, and it seems like the workaround above is incompatible with an arbitrary version of Python from `cachix/nixpkgs-python`.
The error is:
```py
ImportError: /nix/store/flf14c3ibr83jsa070j25hg5gjapydhl-glibc-2.37-8/lib/libc.so.6: version `GLIBC_2.38' not found (required by /nix/store/6zl9iqg8hacf5y0h7b4agc5ym0yxzwa8-devenv-profile/lib/libstdc++.so.6)
```
I guess that version of Python to be using a different glibc version from the one in the `stdenv` (since it's clearly fishy that `glibc-2.37-8` goes looking for glibc 2.38).

Any advice about how to solve this situation?

**Comment by Atry** [comment]
@AleCandido Have you tried `inputs.nixpkgs-python.inputs.nixpkgs.follows = "nixpkgs";`

**Comment by AleCandido** [comment]
Thanks @Atry, I obviously didn't.

It recompiled Python and stopped looking for the wrong version of `glibc`.

**Comment by Atry** [comment]
I just realized there is already a way to specify fallback library path in glibc's dynamic linker:
https://github.com/NixOS/nixpkgs/pull/248547#issuecomment-1995469926

I wonder if we could use LD_AUDIT instead of LD_LIBRARY_PATH to support manylinux ABI?

**Comment by Atry** [comment]
Here is a demo to solve this issue using `LD_AUDIT`: https://github.com/Atry/devenv-ld-floxlib

You can compare the solution with https://github.com/Atry/nix-ld-so-cache-test

**Comment by domenkozar** [comment]
Oh, that's really cool! Would that solve all glibc version incompatibility vues?

**Comment by Atry** [comment]
Yes. glibc should be solved by python’s RUN_PATH, not ld-floxlib

**Comment by Atry** [comment]
libstdc++ would be solved by ld-floxlib’s stdenv. Other shared libraries would be solved by LIB_FLOX_ENV

**Comment by SomeoneSerge** [comment]
> Here is a demo to solve this issue using LD_AUDIT: https://github.com/Atry/devenv-ld-floxlib

You're fast! It would also be nice to provide ld-floxlib in Nixpkgs. Also we could patch it to reproduce the `LD_FALLBACK_PATH` interface too

**Comment by domenkozar** [comment]
I wish someone wrote this in Rust, to be sure it's safe.

**Comment by domenkozar** [comment]
@Atry can you make a PR with a proper implementation using floxlib?

**Comment by Atry** [comment]
@domenkozar Would you mind reviewing other PRs first? https://github.com/cachix/devenv/pull/1018

**Comment by SemMulder** [comment]
> ~I wish someone wrote this in Rust, to be sure it's safe.~ Not possible due to dynamic linker restrictions

@domenkozar can you elaborate why this isn't possible in Rust? I was planning on giving it a try sometime soon ;).

**Comment by Atry** [comment]
I don't know why but I tried to create a LD_AUDIT hook using statically
linked musl instead of glibc and it always crashes.

**Comment by SemMulder** [comment]
> I don't know why but I tried to create a LD_AUDIT hook using statically linked musl instead of glibc and it always crashes.

Might be because `musl` and `glibc` are not binary compatible? Per https://www.musl-libc.org/faq.html:

> Binary compatibility is much more limited, but it will steadily increase with new versions of musl. At present, some glibc-linked shared libraries can be loaded with musl, but all but the simplest glibc-linked applications will fail if musl is dropped-in in place of /lib/ld-linux.so.2.

**Comment by Atry** [comment]
I used to think that a statically linked musl can coexist with a
dynamically linked glibc.

**Comment by jeff-hykin** [comment]
I can't say if the ABI would cause problems, but I can say a statically linked musl with a dynamically linked glibc sounds like a cursed runtime

**Comment by Atry** [comment]
> @Atry can you make a PR with a proper implementation using floxlib?

@domenkozar Do you think https://github.com/DDoSolitary/ld-audit-prefer-runpath would be a better solution, given that a lot of existing softwares are hard-coded to set of get `LD_LIBRARY_PATH`, thus it would not be feasible to replace all `LD_LIBRARY_PATH` usage with `FLOX_ENV`.

**Comment by l0b0** [comment]
Does this also apply to `languages.rust`? I've got a simple Rust language devenv set up. Despite the devenv `packages` containing `pkgs.libxkbcommon`, `cargo run` in the project reports

> xkbcommon\_dl: Failed loading `libxkbcommon-x11.so`. Error: CantOpen(DlOpen { desc: "libxkbcommon-x11.so: cannot open shared object file: No such file or directory" })

`ldd target/debug/program` doesn't mention libxkbcommon, so presumably this is loaded dynamically. How should I deal with this? Do I need to `patchelf` or set `LD_LIBRARY_PATH`?

**Comment by alecandido** [comment]
Uhm, the problem discussed in this issue is exactly with dynamically loaded library. But if the linker is unaware of the library, how is it supposed to go looking for that?

I.e.

> `ldd target/debug/program` doesn't mention libxkbcommon, so presumably this is loaded dynamically. How should I deal with this? Do I need to `patchelf` or set `LD_LIBRARY_PATH`?

`ldd` is listing exactly the libraries that are loaded dynamically.

Maybe it is a transitive dependency. Is it possible?

In any case, the "Nix way", ttbomk, should be to add them to the `rpath` of the compiled program, in case you're making a Nix package. Otherwise, it is correct to extend the `LD_LIBRARY_PATH`, since what you're compiling is not supposed to be specific for a Nix system, so you can't rely on the store path.

Instead, this issue is slightly more specific for Python, since `devenv` is installing the dependencies specified in Nix, but not through the Nix packages. You'd expect them to work out of the box, but they have issues with their own dynamic dependencies.
(Though it would be similar if you have transitive dynamic dependencies of Rust crates, I imagine)
