### ISSUE TITLE
Packaging Keycloak to devenv

### ISSUE THREAD

**Issue by AndreasZeissner** [cachix/devenv#813]
Hi, i recently started to dig my head a bit into devenv and started to work on a service to use keycloak. 

Setting up a basic service is not a problem see https://github.com/AndreasZeissner/devenv/tree/keycloak

I also get keycloak started by using `devenv-test-example keycloak` but it fails with:

```
16:03:04 keycloak.1 | Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
16:03:04 keycloak.1 |   [error]: Build step io.quarkus.deployment.pkg.steps.JarResultBuildStep#buildRunnerJar threw an exception: java.lang.IllegalStateException: java.nio.file.FileSystemException: /nix/store/5jn1nh9vmbxhca5rshjhp1jsvkiwqld3-keycloak-22.0.1/lib/quarkus/generated-bytecode.jar: Read-only file system
16:03:04 keycloak.1 |   at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
16:03:04 keycloak.1 |   at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
16:03:04 keycloak.1 |   at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
16:03:04 keycloak.1 |   at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
16:03:04 keycloak.1 |   at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
16:03:04 keycloak.1 |   at java.base/java.lang.Thread.run(Thread.java:1589)
16:03:04 keycloak.1 |   at org.jboss.threads.JBossThread.run(JBossThread.java:501)
16:03:04 keycloak.1 | Caused by: java.nio.file.FileSystemException: /nix/store/5jn1nh9vmbxhca5rshjhp1jsvkiwqld3-keycloak-22.0.1/lib/quarkus/generated-bytecode.jar: Read-only file system
16:03:04 keycloak.1 |   at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
16:03:04 keycloak.1 |   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
16:03:04 keycloak.1 |   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
16:03:04 keycloak.1 |   at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
16:03:04 keycloak.1 |   at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
16:03:04 keycloak.1 |   at java.base/java.nio.file.Files.delete(Files.java:1152)
16:03:04 keycloak.1 |   at io.quarkus.bootstrap.util.IoUtils.createOrEmptyDir(IoUtils.java:114)
16:03:04 keycloak.1 |   at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:600)
16:03:04 keycloak.1 |   at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:223)
16:03:04 keycloak.1 |   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
16:03:04 keycloak.1 |   at java.base/java.lang.reflect.Method.invoke(Method.java:578)
16:03:04 keycloak.1 |   at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
16:03:04 keycloak.1 |   ... 6 more
16:03:04 keycloak.1 | 
16:03:04 keycloak.1 |   at io.quarkus.builder.Execution.run(Execution.java:123)
16:03:04 keycloak.1 |   at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
16:03:04 keycloak.1 |   at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
16:03:04 keycloak.1 |   at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
16:03:04 keycloak.1 |   ... 24 more
16:03:04 keycloak.1 | Caused by: java.lang.IllegalStateException: java.nio.file.FileSystemException: /nix/store/5jn1nh9vmbxhca5rshjhp1jsvkiwqld3-keycloak-22.0.1/lib/quarkus/generated-bytecode.jar: Read-only file system
16:03:04 keycloak.1 |   at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
16:03:04 keycloak.1 |   at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
16:03:04 keycloak.1 |   at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
16:03:04 keycloak.1 |   at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
16:03:04 keycloak.1 |   at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
16:03:04 keycloak.1 |   at java.base/java.lang.Thread.run(Thread.java:1589)
16:03:04 keycloak.1 |   at org.jboss.threads.JBossThread.run(JBossThread.java:501)
16:03:04 keycloak.1 | Caused by: java.nio.file.FileSystemException: /nix/store/5jn1nh9vmbxhca5rshjhp1jsvkiwqld3-keycloak-22.0.1/lib/quarkus/generated-bytecode.jar: Read-only file system
16:03:04 keycloak.1 |   at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
16:03:04 keycloak.1 |   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
16:03:04 keycloak.1 |   at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
16:03:04 keycloak.1 |   at java.base/sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:248)
16:03:04 keycloak.1 |   at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
16:03:04 keycloak.1 |   at java.base/java.nio.file.Files.delete(Files.java:1152)
16:03:04 keycloak.1 |   at io.quarkus.bootstrap.util.IoUtils.createOrEmptyDir(IoUtils.java:114)
16:03:04 keycloak.1 |   at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildThinJar(JarResultBuildStep.java:600)
16:03:04 keycloak.1 |   at io.quarkus.deployment.pkg.steps.JarResultBuildStep.buildRunnerJar(JarResultBuildStep.java:223)
16:03:04 keycloak.1 |   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
16:03:04 keycloak.1 |   at java.base/java.lang.reflect.Method.invoke(Method.java:578)
16:03:04 keycloak.1 |   at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
16:03:04 keycloak.1 |   ... 6 more
```

I mapped the keycloak configuration (KC_HOME_DIR KC_CONF_DIR) to the `config.env.DEVENV_STATE` directory, I think this is the way to go. 

Looks like that keycloak itself is trying to write something into the nix store and of course fails as the store is read only.

Can you provide any hint on how to handle this, or maybe you know if I am missing something here. 
It could also be something specific to what keycloak does on startup. 

Would be great to get some idea on how this could be solved. 

Thanks

**Comment by tboerger** [comment]
I wanted to have Keycloak running as well and simply failed with it. Running into the same issues without knowing how to get this fixed.

**Comment by sandydoo** [comment]
I don't know much about keycloak, but the nixos module uses `kc.sh start` and not `build`. Might be worth looking at: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/nixos/modules/services/web-apps/keycloak.nix

**Comment by tboerger** [comment]
That's a great hint, I have just tried start-dev command.

**Comment by gabyx** [comment]
I need this too, at the moment. Does it work for now. 
@sandydoo If  somebody has a working example, I am very happy to contribute a `keycloak` module to devenv.
@tboerger : does it work?

**Comment by joas8211** [comment]
It seems that Keycloak service was introduced into devenv in https://github.com/cachix/devenv/pull/1806 🎉 Great job @gabyx!

**Comment by tboerger** [comment]
Looks like we can close this issue now :)
Thanks for the great work!

**Comment by gabyx** [comment]
@sandydoo : Yes we can close this. 🪂 Already successfully using this service in a integration test with devenv etc...

P.S: I will have some more small improvements for the realm export (formatting and sorting by default cause, changes can not be seen in the diff otherwise. We had that in our tooling, buts its better to just add it to the export etc.

**Comment by sandydoo** [comment]
Nice! Well done, everyone!
